[package]
name = "aruga-pretest"
version = "0.1.0"
description = "Project Aruga Profiling Tool - v2 Pretest (desktop)"
authors = ["DSWD Social Technology Bureau"]
edition = "2021"

[lib]
name = "aruga_pretest_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
