<?php
header('Content-Type: application/json');

$locations = [
    'Region I (Ilocos Region)' => [
        'Ilocos Norte' => [
            'Laoag City' => [
                'Barangay 1 - San Lorenzo',
                'Barangay 2 - Santa Joaquina',
                'Barangay 3 - Nuestra Señora del Rosario',
                'Barangay 4 - San Guillermo',
                'Barangay 5 - San Pedro',
                'Barangay 6 - San Agustin',
                'Barangay 7-A - Nuestra Señora de Natividad',
                'Barangay 7-B - Nuestra Señora de Natividad',
                'Barangay 8 - San Vicente',
                'Barangay 9 - Santa Angela',
                'Barangay 10 - San Jose',
                'Barangay 11 - Santa Balbina',
                'Barangay 12 - San Isidro',
                'Barangay 13 - Nuestra Señora de Visitacion',
                'Barangay 14 - Santo Tomas',
                'Barangay 15 - San Guillermo',
                'Barangay 16 - San Jacinto',
                'Barangay 17 - San Francisco',
                'Barangay 18 - San Quirino',
                'Barangay 19 - Santa Marcela',
                'Barangay 20 - San Miguel',
                'Barangay 21 - San Pedro',
                'Barangay 22 - San Andres',
                'Barangay 23 - San Matias',
                'Barangay 24 - Nuestra Señora de Consolacion',
                'Barangay 25 - Santa Cayetana',
                'Barangay 26 - San Marcelino',
                'Barangay 27 - Nuestra Señora de Soledad',
                'Barangay 28 - San Bernardo',
                'Barangay 29 - Santo Tomas',
                'Barangay 30-A - Suyo',
                'Barangay 30-B - Santa Maria',
                'Barangay 31 - Talingaan',
                'Barangay 32-A - La Paz East',
                'Barangay 32-B - La Paz West',
                'Barangay 32-C - La Paz East',
                'Barangay 33-A - La Paz Proper',
                'Barangay 33-B - La Paz Proper',
                'Barangay 34-A - Gabu Norte West',
                'Barangay 34-B - Gabu Norte East',
                'Barangay 35 - Gabu Sur',
                'Barangay 36 - Araniw',
                'Barangay 37 - Calayab',
                'Barangay 38-A - Mangato East',
                'Barangay 38-B - Mangato West',
                'Barangay 39 - Santa Rosa',
                'Barangay 40 - Balatong',
                'Barangay 41 - Balacad',
                'Barangay 42 - Apaya',
                'Barangay 43 - Cavit',
                'Barangay 44 - Zamboanga',
                'Barangay 45 - Tangid',
                'Barangay 46 - Nalbo',
                'Barangay 47 - Bengcag',
                'Barangay 48-A - Cabungaan North',
                'Barangay 48-B - Cabungaan South',
                'Barangay 49-A - Darayday',
                'Barangay 49-B - Raraburan',
                'Barangay 50 - Buttong',
                'Barangay 51-A - Nangalisan East',
                'Barangay 51-B - Nangalisan West',
                'Barangay 52-A - San Mateo',
                'Barangay 52-B - Lataag',
                'Barangay 53 - Rioeng',
                'Barangay 54-A - Lagui-Sail',
                'Barangay 54-B - Camangaan',
                'Barangay 55-A - Barit-Pandan',
                'Barangay 55-B - Salet-Bulangon',
                'Barangay 55-C - Vira',
                'Barangay 56-A - Bacsil North',
                'Barangay 56-B - Bacsil South',
                'Barangay 57 - Pila',
                'Barangay 58 - Casili',
                'Barangay 59-A - Dibua South',
                'Barangay 59-B - Dibua North',
                'Barangay 60-A - Caaoacan',
                'Barangay 60-B - Madiladig',
                'Barangay 61 - Cataban',
                'Barangay 62-A - Navotas North',
                'Barangay 62-B - Navotas South'
            ]
        ]
    ],
    'Region II (Cagayan Valley)' => [
        'Isabela' => [
            'Ilagan City' => [
                'Aggasian',
                'Alibagu',
                'Alinguigan 1st',
                'Alinguigan 2nd',
                'Alinguigan 3rd',
                'Arusip',
                'Baculud',
                'Bagong Silang',
                'Bagumbayan',
                'Baligatan',
                'Ballacong',
                'Bangag',
                'Baraoan',
                'Batong-Labang',
                'Cabeseria 2',
                'Cabeseria 3',
                'Cabeseria 4',
                'Cabeseria 5',
                'Cabeseria 6 & 24',
                'Cabeseria 7',
                'Cabeseria 8',
                'Cabeseria 9 & 11',
                'Cabeseria 10',
                'Cabeseria 14 & 16',
                'Cabeseria 17 & 21',
                'Cabeseria 19',
                'Cabeseria 22',
                'Cabeseria 23',
                'Cabeseria 25',
                'Cabeseria 27',
                'Cabannungan 1st',
                'Cabannungan 2nd',
                'Cadu',
                'Calamagui 1st',
                'Calamagui 2nd',
                'Camunatan',
                'Capellan',
                'Capo',
                'Carikkikan Norte',
                'Carikkikan Sur',
                'Centro Poblacion',
                'Centro-San Antonio',
                'Fugu',
                'Fuyo',
                'Gayong-gayong Norte',
                'Gayong-gayong Sur',
                'Guinatan',
                'Hantas',
                'Imelda Bliss Village',
                'Indagan',
                'Ipalao',
                'Lullutan',
                'Malalam',
                'Malasin',
                'Manaring',
                'Mangcuram',
                'Marana I',
                'Marana II',
                'Marana III',
                'Minabang',
                'Morado',
                'Naguilian Norte',
                'Naguilian Sur',
                'Namnama',
                'Nanaguan',
                'Osmeña',
                'Paliueg',
                'Pasa',
                'Piñares',
                'Quimalabasa',
                'Rang-ayan',
                'Rugao',
                'Saguiguilid del Norte',
                'Saguiguilid del Sur',
                'Salindingan',
                'San Andres',
                'San Felipe',
                'San Ignacio',
                'San Isidro',
                'San Juan',
                'San Lorenzo',
                'San Pablo',
                'San Rodrigo',
                'San Vicente',
                'Santa Barbara',
                'Santa Catalina',
                'Santa Isabel Norte',
                'Santa Isabel Sur',
                'Santo Tomas',
                'Siffu',
                'Sindon Bayabo',
                'Sindon Maride',
                'Sipay',
                'Tangcul',
                'Tegge',
                'Valleyan',
                'Vanutas',
                'Villa Imelda'
            ]
        ]
    ],
    'Region III (Central Luzon)' => [
        'Pampanga' => [
            'Lubao' => [
                'Balantacan',
                'Bancal Pugad',
                'Bancal Sinubli',
                'Baruya',
                'Calangain',
                'Concepcion',
                'De La Paz',
                'Del Carmen',
                'Don Ignacio Dimson',
                'Lourdes',
                'Prado Siongco',
                'Remedios',
                'San Agustin',
                'San Antonio',
                'San Francisco',
                'San Isidro',
                'San Jose Apunan',
                'San Jose Gumi',
                'San Juan',
                'San Matias',
                'San Miguel',
                'San Nicolas 1st',
                'San Nicolas 2nd',
                'San Pablo 1st',
                'San Pablo 2nd',
                'San Pedro Palcarangan',
                'San Pedro Saug',
                'San Roque Arbol',
                'San Roque Dau',
                'San Vicente',
                'Santa Barbara',
                'Santa Catalina',
                'Santa Cruz',
                'Santa Lucia',
                'Santa Maria',
                'Santa Monica',
                'Santa Rita',
                'Santa Teresa 1st',
                'Santa Teresa 2nd',
                'Santiago',
                'Santo Cristo',
                'Santo Domingo',
                'Santo Niño',
                'Santo Tomas'
            ]
        ]
    ],
    'Region IV-A (CALABARZON)' => [
        'Laguna' => [
            'Biñan City' => [
                'Biñan',
                'Bungahan',
                'Canlalay',
                'Casile',
                'De La Paz',
                'Ganado',
                'Langkiwa',
                'Loma',
                'Malaban',
                'Malamig',
                'Mampalasan',
                'Platero',
                'Poblacion',
                'San Antonio',
                'San Francisco',
                'San Jose',
                'San Vicente',
                'Santo Domingo',
                'Santo Niño',
                'Santo Tomas',
                'Soro-soro',
                'Timbao',
                'Tubigan',
                'Zapote'
            ]
        ]
    ],
    'Region IV-B (MIMAROPA)' => [
        'Palawan' => [
            'Puerto Princesa City' => [
                'Babuyan',
                'Bacungan',
                'Bagong Bayan',
                'Bagong Pag-asa',
                'Bagong Sikat',
                'Bagong Silang',
                'Bahile',
                'Bancao-bancao',
                'Barangay ng mga Mangingisda',
                'Binduyan',
                'Buenavista',
                'Cabayugan',
                'Concepcion',
                'Inagawan',
                'Inagawan Sub-Colony',
                'Irawan',
                'Iwahig',
                'Kalipay',
                'Kamuning',
                'Langogan',
                'Liwanag',
                'Lucbuan',
                'Luzviminda',
                'Mabuhay',
                'Macarascas',
                'Magkakaibigan',
                'Maligaya',
                'Manalo',
                'Mandaragat',
                'Manggahan',
                'Maningning',
                'Maoyon',
                'Marufinas',
                'Maruyogon',
                'Masigla',
                'Masikap',
                'Masipag',
                'Matahimik',
                'Matiyaga',
                'Maunlad',
                'Milagrosa',
                'Model',
                'Montible',
                'Napsan',
                'New Panggangan',
                'Pagkakaisa',
                'Princesa',
                'Salvacion',
                'San Jose',
                'San Manuel',
                'San Miguel',
                'San Pedro',
                'San Rafael',
                'Santa Cruz',
                'Santa Lourdes',
                'Santa Lucia',
                'Santa Monica',
                'Seaside',
                'Sicsican',
                'Simpocan',
                'Tagabinit',
                'Tagburos',
                'Tagumpay',
                'Tanabag',
                'Tanglaw',
                'Tiniguiban'
            ]
        ]
    ],
    'Region V (Bicol Region)' => [
        'Sorsogon' => [
            'Sorsogon City' => [
                'Abuyog',
                'Almendras-Cogon',
                'Balete',
                'Balogo (Bacon District)',
                'Balogo (Sorsogon East District)',
                'Barayong',
                'Basud',
                'Bato',
                'Bibincahan',
                'Bitan-o/Dalipay',
                'Bogña',
                'Bon-ot',
                'Bucalbucalan',
                'Buenavista (Bacon District)',
                'Buenavista (Sorsogon East District)',
                'Buhatan',
                'Bulabog',
                'Burabod',
                'Cabarbuhan',
                'Cabid-an',
                'Cambulaga',
                'Capuy',
                'Caricaran',
                'Del Rosario',
                'Gatbo',
                'Gimaloto',
                'Guinlajon',
                'Jamislagan',
                'Macabog',
                'Maricrum',
                'Marinas',
                'Osiao',
                'Pamurayan',
                'Pangpang',
                'Panlayaan',
                'Peñafrancia',
                'Piot',
                'Poblacion',
                'Polvorista',
                'Rawis',
                'Rizal',
                'Salog',
                'Salvacion (Bacon District)',
                'Salvacion (Sorsogon East District)',
                'Sampaloc',
                'San Isidro (Bacon District)',
                'San Isidro (Sorsogon East District)',
                'San Juan (Bacon District)',
                'San Juan (Roro)',
                'San Pascual',
                'San Ramon',
                'San Roque',
                'San Vicente',
                'Santa Cruz',
                'Santa Lucia',
                'Santo Domingo',
                'Santo Niño',
                'Sawanga',
                'Sirangan',
                'Sugod',
                'Sulucan',
                'Talisay',
                'Ticol',
                'Tugos'
            ]
        ]
    ],
    'Region VI (Western Visayas)' => [
        'Antique' => [
            'San Jose de Buenavista' => [
                'Atabay',
                'Badiang',
                'Barangay 1 (Poblacion)',
                'Barangay 2 (Poblacion)',
                'Barangay 3 (Poblacion)',
                'Barangay 4 (Poblacion)',
                'Barangay 5 (Poblacion)',
                'Barangay 6 (Poblacion)',
                'Barangay 7 (Poblacion)',
                'Barangay 8 (Poblacion)',
                'Bariri',
                'Bugarot',
                'Cansadan',
                'Durog',
                'Funda-Dalipe',
                'Igbonglo',
                'Inabasan',
                'Madrangca',
                'Magcalon',
                'Malaiba',
                'Maybato Norte',
                'Maybato Sur',
                'Mojon',
                'Pantao',
                'San Angel',
                'San Fernando',
                'San Pedro',
                'Supa'
            ]
        ]
    ],
    'Region XI (Davao Region)' => [
        'Davao del Sur' => [
            'Sta. Cruz' => [
                'Astorga',
                'Bato',
                'Coronon',
                'Darong',
                'Inawayan',
                'Jose Rizal',
                'Matutungan',
                'Melilia',
                'Saliducon',
                'Sibulan',
                'Sinoron',
                'Tagabuli',
                'Tibolo',
                'Tuban',
                'Zone I (Poblacion)',
                'Zone II (Poblacion)',
                'Zone III (Poblacion)',
                'Zone IV (Poblacion)'
            ]
        ]
    ],
    'NCR (National Capital Region)' => [
        'Metro Manila' => [
            'Caloocan City' => [
                'Barangay 1',
                'Barangay 2',
                'Barangay 3',
                'Barangay 4',
                'Barangay 5',
                'Barangay 6',
                'Barangay 7',
                'Barangay 8',
                'Barangay 9',
                'Barangay 10',
                'Barangay 11',
                'Barangay 12',
                'Barangay 13',
                'Barangay 14',
                'Barangay 15',
                'Barangay 16',
                'Barangay 17',
                'Barangay 18',
                'Barangay 19',
                'Barangay 20',
                'Barangay 21',
                'Barangay 22',
                'Barangay 23',
                'Barangay 24',
                'Barangay 25',
                'Barangay 26',
                'Barangay 27',
                'Barangay 28',
                'Barangay 29',
                'Barangay 30',
                'Barangay 31',
                'Barangay 32',
                'Barangay 33',
                'Barangay 34',
                'Barangay 35',
                'Barangay 36',
                'Barangay 37',
                'Barangay 38',
                'Barangay 39',
                'Barangay 40',
                'Barangay 41',
                'Barangay 42',
                'Barangay 43',
                'Barangay 44',
                'Barangay 45',
                'Barangay 46',
                'Barangay 47',
                'Barangay 48',
                'Barangay 49',
                'Barangay 50',
                'Barangay 51',
                'Barangay 52',
                'Barangay 53',
                'Barangay 54',
                'Barangay 55',
                'Barangay 56',
                'Barangay 57',
                'Barangay 58',
                'Barangay 59',
                'Barangay 60',
                'Barangay 61',
                'Barangay 62',
                'Barangay 63',
                'Barangay 64',
                'Barangay 65',
                'Barangay 66',
                'Barangay 67',
                'Barangay 68',
                'Barangay 69',
                'Barangay 70',
                'Barangay 71',
                'Barangay 72',
                'Barangay 73',
                'Barangay 74',
                'Barangay 75',
                'Barangay 76',
                'Barangay 77',
                'Barangay 78',
                'Barangay 79',
                'Barangay 80',
                'Barangay 81',
                'Barangay 82',
                'Barangay 83',
                'Barangay 84',
                'Barangay 85',
                'Barangay 86',
                'Barangay 87',
                'Barangay 88',
                'Barangay 89',
                'Barangay 90',
                'Barangay 91',
                'Barangay 92',
                'Barangay 93',
                'Barangay 94',
                'Barangay 95',
                'Barangay 96',
                'Barangay 97',
                'Barangay 98',
                'Barangay 99',
                'Barangay 100',
                'Barangay 101',
                'Barangay 102',
                'Barangay 103',
                'Barangay 104',
                'Barangay 105',
                'Barangay 106',
                'Barangay 107',
                'Barangay 108',
                'Barangay 109',
                'Barangay 110',
                'Barangay 111',
                'Barangay 112',
                'Barangay 113',
                'Barangay 114',
                'Barangay 115',
                'Barangay 116',
                'Barangay 117',
                'Barangay 118',
                'Barangay 119',
                'Barangay 120',
                'Barangay 121',
                'Barangay 122',
                'Barangay 123',
                'Barangay 124',
                'Barangay 125',
                'Barangay 126',
                'Barangay 127',
                'Barangay 128',
                'Barangay 129',
                'Barangay 130',
                'Barangay 131',
                'Barangay 132',
                'Barangay 133',
                'Barangay 134',
                'Barangay 135',
                'Barangay 136',
                'Barangay 137',
                'Barangay 138',
                'Barangay 139',
                'Barangay 140',
                'Barangay 141',
                'Barangay 142',
                'Barangay 143',
                'Barangay 144',
                'Barangay 145',
                'Barangay 146',
                'Barangay 147',
                'Barangay 148',
                'Barangay 149',
                'Barangay 150',
                'Barangay 151',
                'Barangay 152',
                'Barangay 153',
                'Barangay 154',
                'Barangay 155',
                'Barangay 156',
                'Barangay 157',
                'Barangay 158',
                'Barangay 159',
                'Barangay 160',
                'Barangay 161',
                'Barangay 162',
                'Barangay 163',
                'Barangay 164',
                'Barangay 165',
                'Barangay 166',
                'Barangay 167',
                'Barangay 168',
                'Barangay 169',
                'Barangay 170',
                'Barangay 171',
                'Barangay 172',
                'Barangay 173',
                'Barangay 174',
                'Barangay 175',
                'Barangay 176',
                'Barangay 177',
                'Barangay 178',
                'Barangay 179',
                'Barangay 180',
                'Barangay 181',
                'Barangay 182',
                'Barangay 183',
                'Barangay 184',
                'Barangay 185',
                'Barangay 186',
                'Barangay 187',
                'Barangay 188'
            ]
        ]
    ]
];

echo json_encode($locations, JSON_PRETTY_PRINT);
?>
