<?php
header('Access-Control-Allow-Origin: *');
header('Content-Type: application/json');

$locations = [
    'Region I (Ilocos Region)' => [
        'Ilocos Norte' => [
            'Laoag City' => [
                'Barangay 1 (Pob.)',
                'Barangay 2 (Pob.)',
                'Barangay 3 (Pob.)',
                'Barangay 4 (Pob.)',
                'Barangay 5 (Pob.)',
                'Barangay 6 (Pob.)',
                'Barangay 7 (Pob.)',
                'Barangay 8 (Pob.)',
                'Barangay 9 (Pob.)',
                'Barangay 10 (Pob.)',
                'Barangay 11 (Pob.)',
                'Barangay 12 (Pob.)',
                'Barangay 13 (Pob.)',
                'Barangay 14 (Pob.)',
                'Barangay 15 (Pob.)',
                'Barangay 16 (Pob.)',
                'Barangay 17 (Pob.)',
                'Barangay 18 (Pob.)',
                'Barangay 19 (Pob.)',
                'Barangay 20 (Pob.)',
                'Barangay 21 (Pob.)',
                'Barangay 22 (Pob.)',
                'Barangay 23 (Pob.)',
                'Barangay 24 (Pob.)',
                'Barangay 25 (Pob.)',
                'Barangay 26 (Pob.)',
                'Barangay 27 (Pob.)',
                'Barangay 28 (Pob.)',
                'Barangay 29 (Pob.)',
                'Barangay 30 (Pob.)',
                'Barangay 31 (Pob.)',
                'Barangay 32 (Pob.)',
                'Barangay 33 (Pob.)',
                'Barangay 34 (Pob.)',
                'Barangay 35 (Pob.)',
                'Barangay 36 (Pob.)',
                'Barangay 37 (Pob.)',
                'Barangay 38 (Pob.)',
                'Barangay 39 (Pob.)',
                'Barangay 40 (Pob.)',
                'Barangay 41 (Pob.)',
                'Barangay 42 (Pob.)',
                'Barangay 43 (Pob.)',
                'Barangay 44 (Pob.)',
                'Barangay 45 (Pob.)',
                'Barangay 46 (Pob.)',
                'Barangay 47 (Pob.)',
                'Barangay 48 (Pob.)',
                'Ablan',
                'Bongro',
                'Cabungaran',
                'Cataban',
                'Gabu',
                'Nangalisan',
                'Raraburan',
                'San Nicolas',
                'Suyo',
                'Talingaan'
            ]
        ]
    ],
    'Region II (Cagayan Valley)' => [
        'Isabela' => [
            'Ilagan City' => [
                'Alibagu',
                'Alloy',
                'Arusip',
                'Bagong Silang',
                'Baligatan',
                'Bannawag',
                'Buenavista',
                'Cabesera',
                'Calamagui 1st',
                'Calamagui 2nd',
                'Centro 1 (Pob.)',
                'Centro 2 (Pob.)',
                'Centro 3 (Pob.)',
                'Centro 4 (Pob.)',
                'Centro 5 (Pob.)',
                'Centro 6 (Pob.)',
                'Centro 7 (Pob.)',
                'Centro 8 (Pob.)',
                'Imelda',
                'Lullutan',
                'Manano',
                'Marana',
                'Minabang',
                'Morado',
                'Naguilian',
                'Naneng',
                'San Felipe',
                'San Isidro',
                'San Juan',
                'San Vicente',
                'Santa Maria',
                'Santo Tomas',
                'Sinippil',
                'Tangab',
                'Ugad',
                'Villa Imelda'
            ]
        ]
    ],
    'Region III (Central Luzon)' => [
        'Pampanga' => [
            'Lubao' => [
                'Balantacan',
                'Bancal Pugad',
                'Bancal Sinubli',
                'Baruya (Santa Monica)',
                'Calangain',
                'Concepcion',
                'De La Paz',
                'Del Carmen',
                'Lourdes (Lauc Pau)',
                'Prado Siongco',
                'San Agustin',
                'San Antonio',
                'San Isidro',
                'San Jose',
                'San Juan Bautista',
                'San Juan Nepomuceno',
                'San Nicolas 1st',
                'San Nicolas 2nd',
                'San Pablo 1st',
                'San Pablo 2nd',
                'San Pedro',
                'San Rafael',
                'San Roque',
                'Santa Catalina',
                'Santa Cruz',
                'Santa Lucia',
                'Santa Maria',
                'Santo Domingo',
                'Santo Tomas',
                'Seroro',
                'Sta. Cruz Nuevo',
                'Sto. Cristo',
                'Sulipan',
                'Tigbe'
            ]
        ]
    ],
    'Region IV-A (CALABARZON)' => [
        'Laguna' => [
            'Binan City' => [
                'Bungahan',
                'Canlalay',
                'Casile',
                'De La Paz',
                'Ganado',
                'Langkiwa',
                'Loma',
                'Malaban',
                'Malamig',
                'Mamplasan',
                'Platero',
                'Poblacion',
                'San Antonio',
                'San Francisco (Halang)',
                'San Jose',
                'San Vicente',
                'Santo Domingo',
                'Santo Tomas',
                'Soro-soro',
                'Timbao',
                'Tubigan',
                'Zapote'
            ]
        ]
    ],
    'MIMAROPA' => [
        'Palawan' => [
            'Puerto Princesa City' => [
                'Bagong Bayan',
                'Bagong Sikat',
                'Bahile',
                'Bancao-Bancao',
                'Binduyan',
                'Buenavista',
                'Cabayugan',
                'Concepcion',
                'Inagawan',
                'Inagawan Sub-Colony',
                'Irawan',
                'Iwahig (Pob.)',
                'Kalipay (Pob.)',
                'Kamuning',
                'Langogan',
                'Liwanag (Pob.)',
                'Lucbuan',
                'Luzviminda',
                'Mabuhay (Pob.)',
                'Macarascas',
                'Mandaragat',
                'Manggahan (Pob.)',
                'Maningning (Pob.)',
                'Marufinas',
                'Maruyogon',
                'Masigla (Pob.)',
                'Masipag (Pob.)',
                'Matahimik (Pob.)',
                'Matiyaga (Pob.)',
                'Maunlad (Pob.)',
                'Milagrosa (Pob.)',
                'Model (Pob.)',
                'Montible (Pob.)',
                'Napsan',
                'New Panggangan',
                'Pagkakaisa (Pob.)',
                'Princesa',
                'San Jose',
                'San Manuel',
                'San Miguel',
                'San Pedro',
                'San Rafael',
                'Santa Cruz',
                'Santa Lourdes',
                'Santa Lucia',
                'Santa Monica',
                'Sicsican',
                'Simpocan',
                'Tagburos',
                'Tagumpay (Pob.)',
                'Tiniguiban'
            ]
        ]
    ],
    'Region V (Bicol)' => [
        'Sorsogon' => [
            'Sorsogon City' => [
                'Abuyog',
                'Almendras-Cogon (Pob.)',
                'Bacon',
                'Balete',
                'Bibincahan',
                'Bitan-o/Dalipay (Pob.)',
                'Bucalbucalan',
                'Buenavista',
                'Buhatan',
                'Bulabog',
                'Burabod (Pob.)',
                'Cabid-an',
                'Capuy',
                'Casili',
                'Castilla',
                'Centro (Pob.)',
                'Cogon',
                'Cotmon',
                'Dalakit (Pob.)',
                'Gateway (Pob.)',
                'Guinlajon',
                'Gulang-gulang',
                'Hamtic',
                'Irrigon',
                'Magsaysay',
                'Marog',
                'Panlayaan',
                'Peñafrancia',
                'Polvorista (Pob.)',
                'Quezon',
                'Rawis',
                'Rizal',
                'Salog (Pob.)',
                'Sampaloc',
                'San Isidro',
                'San Juan',
                'San Pablo',
                'Santa Cruz',
                'Sapngan (Pob.)',
                'Sugod',
                'Talisay',
                'Tondol',
                'Tugos'
            ]
        ]
    ],
    'Region VI (Western Visayas)' => [
        'Antique' => [
            'San Jose De Buenavista' => [
                'Badiang',
                'Balanac',
                'Bugarot',
                'Cagban',
                'Canatuan',
                'Cato',
                'Dawis',
                'Linaban',
                'Mag-aba',
                'Magbato',
                'Malaiba',
                'Maybato Norte',
                'Maybato Sur',
                'Ongyod',
                'Osorio',
                'Pajo',
                'Palje',
                'Paltok',
                'Poblacion 1',
                'Poblacion 2',
                'Poblacion 3',
                'Poblacion 4',
                'Poblacion 5',
                'Poblacion 6',
                'Poblacion 7',
                'Poblacion 8',
                'Poblacion 9',
                'Poblacion 10',
                'San Fernando',
                'Taldak'
            ]
        ]
    ],
    'Region XI (Davao)' => [
        'Davao del Sur' => [
            'Sta. Cruz' => [
                'Astorga',
                'Balasinon',
                'Buguis',
                'Cabligan (Manle)',
                'Camanchiles',
                'Ceboza',
                'Coronobe',
                'Hagonoy',
                'Inawayan',
                'Jose Rizal',
                'Kiblagon',
                'La Paz',
                'Lacaron',
                'Mabini',
                'Malalag',
                'Malasila',
                'Malaya',
                'Napungas',
                'New Baclayon',
                'Patulang',
                'San Isidro',
                'San Marcos',
                'Santa Cruz (Pob.)',
                'Santo Niño',
                'Tagansule'
            ]
        ]
    ],
    'NCR (National Capital Region)' => [
        'Metro Manila' => [
            'Caloocan City' => [
                'Barangay 1 (Pob.)',
                'Barangay 2 (Pob.)',
                'Barangay 3 (Pob.)',
                'Barangay 4 (Pob.)',
                'Barangay 5 (Pob.)',
                'Barangay 6 (Pob.)',
                'Barangay 7 (Pob.)',
                'Barangay 8 (Pob.)',
                'Barangay 9 (Pob.)',
                'Barangay 10 (Pob.)',
                'Barangay 11 (Pob.)',
                'Barangay 12 (Pob.)',
                'Barangay 13 (Pob.)',
                'Barangay 14 (Pob.)',
                'Barangay 15 (Pob.)',
                'Barangay 16 (Pob.)',
                'Barangay 17 (Pob.)',
                'Barangay 18 (Pob.)',
                'Barangay 19 (Pob.)',
                'Barangay 20 (Pob.)',
                'Barangay 21 (Pob.)',
                'Barangay 22 (Pob.)',
                'Barangay 23 (Pob.)',
                'Barangay 24 (Pob.)',
                'Barangay 25 (Pob.)',
                'Barangay 26 (Pob.)',
                'Barangay 27 (Pob.)',
                'Barangay 28 (Pob.)',
                'Barangay 29 (Pob.)',
                'Barangay 30 (Pob.)',
                'Barangay 31 (Pob.)',
                'Barangay 32 (Pob.)',
                'Barangay 33 (Pob.)',
                'Barangay 34 (Pob.)',
                'Barangay 35 (Pob.)',
                'Barangay 36 (Pob.)',
                'Barangay 37 (Pob.)',
                'Barangay 38 (Pob.)',
                'Barangay 39 (Pob.)',
                'Barangay 40 (Pob.)',
                'Barangay 41 (Pob.)',
                'Barangay 42 (Pob.)',
                'Barangay 43 (Pob.)',
                'Barangay 44 (Pob.)',
                'Barangay 45 (Pob.)',
                'Barangay 46 (Pob.)',
                'Barangay 47 (Pob.)',
                'Barangay 48 (Pob.)',
                'Barangay 49 (Pob.)',
                'Barangay 50 (Pob.)',
                'Bagong Silang',
                'Camarin',
                'Deparo',
                'Llano',
                'Maypajo',
                'Paltok',
                'Sangandaan',
                'Tala',
                'Tibagan',
                'University Hills'
            ]
        ]
    ]
];

echo json_encode($locations, JSON_PRETTY_PRINT);
?>
